POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@mail.com",
    "password": "admin",
    "role": "ADMIN"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwicm9sZSI6IkFETUlOIiwic3ViIjoiY205MzJtZHhoMDAwMDRwdjlnMGw4MjRwOSIsImlhdCI6MTc0Mzg5NTI3NSwiZXhwIjoxNzQzOTIwNDc1fQ.k5jU0uxwvLgYzEBxvWoHARo1ms_kzw031rCVuHcX4sE

###
GET http://localhost:3000/users/cm932mdxh00004pv9g0l824p9

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin"
}